### ISSUE TITLE
Why DuckDuckGo?

### ISSUE THREAD

**Issue by abehr** [steamp0rt/Big-Ol-Privacy-Guide#1]
I arrived here via the link you added onto your old [Reddit post](https://np.reddit.com/r/pcmasterrace/comments/8sffn7/pc_users_guide_to_privacy/). Thanks for putting this together, it's super helpful!

I noticed that in the old guide you specifically called out DuckDuckGo as not recommended, but in this guide you do. Just curious about what they changed to garner your recommendation?

**Comment by steamp0rt** [comment]
Nothing. I just realized it was a dumb idea to ignore it.
